name: Deploy Example
on: [workflow_dispatch]
# on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: STAGING  # This triggers the protection rule
    steps:
      - run: echo "Deploying to production"
