name: sample workflow
on: [workflow_dispatch]
jobs:
  my-job:
    runs-on: ubuntu-latest
    timeout-minutes: 1 # Set the job timeout to 10 minutes

    steps:
      # Your workflow steps
      - name: Run a command
        run: |
          echo "Starting a long-running process..."
          sleep 65 # Sleep for 10 minutes to cause a timeout
          echo "Process finished."
